version: "3"

services:
  server:
    build: ./
    ports:
      - "8080:9000"
    volumes:
      - ./:/app
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://admin:admin@mongo:27017/
      - MONGO_DB_DATABASE=bingo

  mongo:
    image: "mongo:latest"
    container_name: "bingo-db"
    environment:
      - MONGO_INITDB_DATABASE=bingo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017-27019:27017-27019"
